# Generated by Django 4.2.19 on 2025-03-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.JSONField(default=list)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
